import 'package:flutter/foundation.dart';

class AppLocale {
  static final ValueNotifier<String> language = ValueNotifier<String>('en');
}

const _pl = <String, String>{
  'dashboard': 'Start',
  'vehicles': 'Pojazdy',
  'drivers': 'Kierowcy',
  'issues': 'Usterki',
  'repairs': 'Naprawy',
  'garages': 'Warsztaty',
  'company': 'Firma',
  'more': 'Więcej',
  'refresh': 'Odśwież',
  'sign_out': 'Wyloguj',
  'language': 'Język',
  'settings': 'Ustawienia',
  'team': 'Zespół',
  'team_description': 'Osoby mające dostęp do tej floty',
  'invite_member': 'Zaproś użytkownika',
  'email': 'E-mail',
  'role': 'Rola',
  'create_invite': 'Utwórz zaproszenie',
  'invite_created': 'Link zaproszenia został skopiowany',
  'pending_invites': 'Oczekujące zaproszenia',
  'no_invites': 'Brak oczekujących zaproszeń',
  'revoke': 'Anuluj',
  'remove': 'Usuń',
  'join_company': 'Dołącz do istniejącej firmy',
  'invite_code': 'Kod zaproszenia',
  'accept_invite': 'Dołącz',
  'members': 'Członkowie zespołu',
  'your_role': 'Twoja rola',
  'currency': 'Waluta',
  'polish': 'Polski',
  'english': 'English',
  'owner': 'Właściciel',
  'admin': 'Administrator',
  'manager': 'Manager',
  'viewer': 'Podgląd',
  'try_again': 'Spróbuj ponownie',
  'create_account': 'Utwórz konto',
  'sign_in': 'Zaloguj',
  'sign_in_subtitle': 'Zaloguj się do swojej floty',
  'password': 'Hasło',
  'have_account': 'Masz już konto? Zaloguj się',
  'no_account': 'Nie masz konta? Utwórz je',
  'invalid_email': 'Podaj poprawny adres e-mail',
  'short_password': 'Hasło musi mieć co najmniej 8 znaków',
  'available': 'Dostępny',
  'in_use': 'W użyciu',
  'workshop': 'Warsztat',
  'maintenance': 'Serwis',
  'off_road': 'Wyłączony z ruchu',
  'sold': 'Sprzedany',
  'active': 'Aktywny',
  'inactive': 'Nieaktywny',
  'holiday': 'Urlop',
  'suspended': 'Zawieszony',
  'low': 'Niski',
  'medium': 'Średni',
  'high': 'Wysoki',
  'critical': 'Krytyczny',
  'open': 'Otwarta',
  'booked': 'Umówiona',
  'in_progress': 'W trakcie',
  'resolved': 'Rozwiązana',
  'closed': 'Zamknięta',
  'planned': 'Planowana',
  'ready': 'Gotowa',
  'completed': 'Zakończona',
  'cancelled': 'Anulowana',
};

const _en = <String, String>{
  'dashboard': 'Home',
  'vehicles': 'Vehicles',
  'drivers': 'Drivers',
  'issues': 'Issues',
  'repairs': 'Repairs',
  'garages': 'Garages',
  'company': 'Company',
  'more': 'More',
  'refresh': 'Refresh',
  'sign_out': 'Sign out',
  'language': 'Language',
  'settings': 'Settings',
  'team': 'Team',
  'team_description': 'People with access to this fleet',
  'invite_member': 'Invite user',
  'email': 'Email',
  'role': 'Role',
  'create_invite': 'Create invitation',
  'invite_created': 'Invitation link copied',
  'pending_invites': 'Pending invitations',
  'no_invites': 'No pending invitations',
  'revoke': 'Revoke',
  'remove': 'Remove',
  'join_company': 'Join an existing company',
  'invite_code': 'Invitation code',
  'accept_invite': 'Join',
  'members': 'Team members',
  'your_role': 'Your role',
  'currency': 'Currency',
  'polish': 'Polski',
  'english': 'English',
  'owner': 'Owner',
  'admin': 'Administrator',
  'manager': 'Manager',
  'viewer': 'Viewer',
  'try_again': 'Try again',
  'create_account': 'Create account',
  'sign_in': 'Sign in',
  'sign_in_subtitle': 'Sign in to your fleet',
  'password': 'Password',
  'have_account': 'Already have an account? Sign in',
  'no_account': 'New to FleetPilot? Create an account',
  'invalid_email': 'Enter a valid email',
  'short_password': 'Use at least 8 characters',
  'available': 'Available',
  'in_use': 'In use',
  'workshop': 'Workshop',
  'maintenance': 'Maintenance',
  'off_road': 'Off road',
  'sold': 'Sold',
  'active': 'Active',
  'inactive': 'Inactive',
  'holiday': 'Holiday',
  'suspended': 'Suspended',
  'low': 'Low',
  'medium': 'Medium',
  'high': 'High',
  'critical': 'Critical',
  'open': 'Open',
  'booked': 'Booked',
  'in_progress': 'In progress',
  'resolved': 'Resolved',
  'closed': 'Closed',
  'planned': 'Planned',
  'ready': 'Ready',
  'completed': 'Completed',
  'cancelled': 'Cancelled',
};

String tr(String key) {
  final map = AppLocale.language.value == 'pl' ? _pl : _en;
  return map[key] ?? key;
}
